service: email-service

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: us-east-1
  environment:
    SMTP_HOST: ${env:SMTP_HOST}
    SMTP_PORT: ${env:SMTP_PORT}
    SMTP_USER: ${env:SMTP_USER}
    SMTP_PASSWORD: ${env:SMTP_PASSWORD}

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send
          method: post
          cors: true